# Generated by Django 5.0.6 on 2024-05-16 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0002_assistant_judge_alter_query_query_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='assistant_name',
            field=models.CharField(max_length=150, verbose_name='ФИО помощника'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=20, verbose_name='номер дела'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='judge_name',
            field=models.CharField(max_length=150, verbose_name='ФИО судьи'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority_name',
            field=models.CharField(max_length=50, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_comments',
            field=models.TextField(verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='law_app.status'),
        ),
        migrations.AlterField(
            model_name='querytype',
            name='query_type_name',
            field=models.CharField(max_length=200, verbose_name='тип запроса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=30, verbose_name='статус'),
        ),
    ]
