# Generated by Django 5.0.6 on 2024-05-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0003_alter_assistant_assistant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_comments',
            field=models.TextField(verbose_name='комментарии'),
        ),
    ]
