# Generated by Django 5.0.6 on 2024-05-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_app', '0004_alter_query_query_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'erkjhjfkejf'},
        ),
    ]
